#!/usr/bin/env python3
"""Build the PYTHIA pathway data.

Checks performed:

  * EC numbers have the right shape: four dot-separated fields, the first
    a class between 1 and 7. This catches transposed digits and missing
    fields. It cannot catch a number that is well formed and wrong.
  * every molecule id cited exists in the library
  * every source key resolves

The build prints how many EC numbers are awaiting confirmation against
ExplorEnz, because a check that only validates shape should not be allowed
to feel like a check that validates meaning.

Output: ../data/pathways.js
"""

import json
import os
import re
import sys

from library import LIBRARY
from pathways import PATHWAYS
from sources import resolve

OUT = os.path.join(os.path.dirname(__file__), "..", "data", "pathways.js")

EC_SHAPE = re.compile(r"^[1-7]\.\d{1,2}\.\d{1,3}\.[\dn]{1,3}$")


def main():
    known = set(entry.id for entry in LIBRARY)
    problems = []
    out = []
    ec_count = 0

    for path in PATHWAYS:
        steps = []
        for i, step in enumerate(path.steps, start=1):
            where = "%s step %d" % (path.id, i)

            if not EC_SHAPE.match(step.ec):
                problems.append("%s: EC number %r is not well formed"
                                % (where, step.ec))
            else:
                ec_count += 1

            if step.molecule and step.molecule not in known:
                problems.append("%s cites unknown molecule '%s'"
                                % (where, step.molecule))

            steps.append({
                "substrate": step.substrate,
                "product": step.product,
                "enzyme": step.enzyme,
                "ec": step.ec,
                "cofactors": list(step.cofactors),
                "reversible": step.reversible,
                "note": step.note,
                "key": step.key,
                "molecule": step.molecule,
            })

        try:
            srcs = resolve(path.sources)
        except KeyError as exc:
            problems.append("%s: %s" % (path.id, exc))
            continue

        out.append({
            "id": path.id,
            "name": path.name,
            "summary": path.summary,
            "location": path.location,
            "purpose": path.purpose,
            "regulation": path.regulation,
            "steps": steps,
            "sources": srcs,
        })

    if problems:
        print("FAILED:")
        for p in problems:
            print("  -", p)
        return 1

    payload = json.dumps(out, ensure_ascii=True, separators=(",", ":"))
    with open(OUT, "w", encoding="ascii") as fh:
        fh.write("/* PYTHIA metabolic pathways.\n"
                 "   Generated by tools/build_pathways.py -- "
                 "do not edit by hand.\n"
                 "   %d pathways. EC numbers are shape-checked only; see\n"
                 "   tools/pathways.py for what that does and does not "
                 "mean. */\n" % len(out))
        fh.write("window.PYTHIA_PATHWAYS = ")
        fh.write(payload)
        fh.write(";\n")

    total = sum(len(p["steps"]) for p in out)
    keys = sum(1 for p in out for s in p["steps"] if s["key"])
    irrev = sum(1 for p in out for s in p["steps"] if not s["reversible"])
    print("built %d pathways, %d steps -> %s (%.0f kB)"
          % (len(out), total, os.path.relpath(OUT),
             os.path.getsize(OUT) / 1024))
    print("%d regulated or committed steps, %d irreversible" % (keys, irrev))
    print("%d EC numbers well formed -- shape only, still to be confirmed "
          "against ExplorEnz" % ec_count)
    return 0


if __name__ == "__main__":
    sys.exit(main())
