#!/usr/bin/env python3
"""Build the PYTHIA element table.

Atomic weights and isotope abundances are taken from RDKit's periodic
table rather than transcribed by hand. Hand-copied numeric tables are a
known source of quiet, permanent errors: a transposed digit in an atomic
weight is invisible in review and wrong in every calculation downstream
forever.

Emitted for every element that has at least one isotope with a measured
natural abundance. Elements with no stable isotopes carry a standard
atomic weight but no distribution, so molar mass works for them and
isotopic patterns do not, which is the correct behaviour.

Output: ../data/elements.js
"""

import json
import os
import sys

from rdkit import Chem

OUT = os.path.join(os.path.dirname(__file__), "..", "data", "elements.js")

MAX_Z = 103          # through lawrencium; beyond that nothing is useful here
MIN_ABUNDANCE = 1e-6  # percent, below which an isotope is noise for teaching


def main():
    pt = Chem.GetPeriodicTable()
    elements = {}
    with_isotopes = 0

    for z in range(1, MAX_Z + 1):
        try:
            symbol = pt.GetElementSymbol(z)
            weight = pt.GetAtomicWeight(z)
        except Exception:
            continue
        if not symbol or symbol.startswith("*"):
            continue

        isotopes = []
        for mass_number in range(1, 300):
            abundance = pt.GetAbundanceForIsotope(z, mass_number)
            if abundance <= MIN_ABUNDANCE:
                continue
            isotopes.append([
                round(pt.GetMassForIsotope(z, mass_number), 8),
                round(abundance / 100.0, 8),        # stored as a fraction
            ])

        entry = {
            "z": z,
            "weight": round(weight, 6),
            "valence": pt.GetDefaultValence(z),
        }
        if isotopes:
            isotopes.sort(key=lambda pair: -pair[1])
            entry["isotopes"] = isotopes
            entry["mono"] = isotopes[0][0]
            with_isotopes += 1

        elements[symbol] = entry

    # The abundances should each sum to 1 within rounding. A element that
    # does not is a data problem, not a rounding problem.
    off = []
    for symbol, entry in elements.items():
        if "isotopes" not in entry:
            continue
        total = sum(pair[1] for pair in entry["isotopes"])
        if abs(total - 1.0) > 5e-4:
            off.append((symbol, total))
    if off:
        print("FAILED: isotope abundances do not sum to 1:")
        for symbol, total in off:
            print("  - %s: %.6f" % (symbol, total))
        return 1

    with open(OUT, "w", encoding="ascii") as fh:
        fh.write("/* PYTHIA element data.\n"
                 "   Generated by tools/build_elements.py -- "
                 "do not edit by hand.\n"
                 "   Standard atomic weights and natural isotope "
                 "abundances via RDKit. */\n")
        fh.write("window.PYTHIA_ELEMENTS = ")
        fh.write(json.dumps(elements, ensure_ascii=True, sort_keys=True,
                            separators=(",", ":")))
        fh.write(";\n")

    print("built %d elements (%d with a natural isotope distribution) "
          "-> %s (%.0f kB)"
          % (len(elements), with_isotopes, os.path.relpath(OUT),
             os.path.getsize(OUT) / 1024))
    print("every isotope distribution sums to 1 within 5e-4")
    return 0


if __name__ == "__main__":
    sys.exit(main())
