#!/usr/bin/env python3
"""Build the PYTHIA nomenclature data.

The check that matters: concatenating the pieces of a decomposed name must
reproduce that molecule's name character for character. A decomposition
that does not spell the name is teaching a construction the name does not
have, and there is no way to notice that by looking at the rendered page.

Also checks, as elsewhere, that every molecule id cited exists.

Output: ../data/nomenclature.js
"""

import json
import os
import sys

from library import LIBRARY
from nomenclature import NAMES, RULES, SENIORITY, SOURCES as NOM_SOURCES
from sources import resolve

OUT = os.path.join(os.path.dirname(__file__), "..", "data", "nomenclature.js")


def main():
    by_id = {entry.id: entry for entry in LIBRARY}
    problems = []

    # --- rules ------------------------------------------------------------
    rules = []
    for rule in RULES:
        for i, block in enumerate(rule.blocks):
            for mol_id in block.get("ids", []):
                if mol_id not in by_id:
                    problems.append("rule %s block %d cites unknown molecule "
                                    "'%s'" % (rule.id, i, mol_id))
        rules.append({"id": rule.id, "title": rule.title,
                      "blocks": rule.blocks})

    # --- worked names -----------------------------------------------------
    names = []
    for worked in NAMES:
        entry = by_id.get(worked.molecule)
        if entry is None:
            problems.append("worked name cites unknown molecule '%s'"
                            % worked.molecule)
            continue

        spelled = "".join(part["text"] for part in worked.parts)
        if spelled != entry.name:
            problems.append(
                "'%s': the pieces spell %r but the molecule is named %r"
                % (worked.molecule, spelled, entry.name))
            continue

        names.append({
            "molecule": worked.molecule,
            "name": entry.name,
            "parts": worked.parts,
            "commentary": worked.commentary,
        })

    # --- seniority table --------------------------------------------------
    table = []
    for group in SENIORITY:
        if group.example and group.example not in by_id:
            problems.append("seniority row '%s' cites unknown molecule '%s'"
                            % (group.name, group.example))
            continue
        table.append({
            "rank": group.rank, "name": group.name,
            "suffix": group.suffix, "prefix": group.prefix,
            "example": group.example,
        })

    if problems:
        print("FAILED:")
        for p in problems:
            print("  -", p)
        return 1

    payload = {
        "rules": rules,
        "names": names,
        "seniority": table,
        "sources": resolve(NOM_SOURCES),
    }

    with open(OUT, "w", encoding="ascii") as fh:
        fh.write("/* PYTHIA nomenclature.\n"
                 "   Generated by tools/build_nomenclature.py -- "
                 "do not edit by hand. */\n")
        fh.write("window.PYTHIA_NOMENCLATURE = ")
        fh.write(json.dumps(payload, ensure_ascii=True,
                            separators=(",", ":")))
        fh.write(";\n")

    pieces = sum(len(n["parts"]) for n in names)
    print("built %d rules, %d worked names (%d pieces), %d seniority rows "
          "-> %s (%.0f kB)"
          % (len(rules), len(names), pieces, len(table),
             os.path.relpath(OUT), os.path.getsize(OUT) / 1024))
    print("every decomposition spells its molecule's name exactly")
    return 0


if __name__ == "__main__":
    sys.exit(main())
