#!/usr/bin/env python3
"""Build the PYTHIA lesson data.

The lessons are prose, so there is nothing to compute. What this does is
check them:

  * every molecule id cited by a lesson must exist in the library
  * every source key must resolve

Both failures are silent at runtime. A lesson citing a renamed molecule
renders an empty box, and an unsourced claim looks exactly like a sourced
one. Catching them here is the only place it is cheap.

Output: ../data/lessons.js
"""

import json
import os
import sys

from lessons import LESSONS
from library import LIBRARY
from sources import resolve

OUT = os.path.join(os.path.dirname(__file__), "..", "data", "lessons.js")


def main():
    known = set(entry.id for entry in LIBRARY)
    problems = []
    out = []
    cited = set()

    for lesson in LESSONS:
        for i, block in enumerate(lesson.blocks):
            for mol_id in block.get("ids", []):
                cited.add(mol_id)
                if mol_id not in known:
                    problems.append(
                        "%s block %d cites unknown molecule '%s'"
                        % (lesson.id, i, mol_id))
        try:
            srcs = resolve(lesson.sources)
        except KeyError as exc:
            problems.append("%s: %s" % (lesson.id, exc))
            continue

        out.append({
            "id": lesson.id,
            "title": lesson.title,
            "blurb": lesson.blurb,
            "blocks": lesson.blocks,
            "sources": srcs,
        })

    if problems:
        print("FAILED:")
        for p in problems:
            print("  -", p)
        return 1

    payload = json.dumps(out, ensure_ascii=True, separators=(",", ":"))
    with open(OUT, "w", encoding="ascii") as fh:
        fh.write("/* PYTHIA stereochemistry lessons.\n"
                 "   Generated by tools/build_lessons.py -- "
                 "do not edit by hand.\n"
                 "   %d lessons. */\n" % len(out))
        fh.write("window.PYTHIA_LESSONS = ")
        fh.write(payload)
        fh.write(";\n")

    blocks = sum(len(l["blocks"]) for l in out)
    print("built %d lessons, %d blocks -> %s (%.0f kB)"
          % (len(out), blocks, os.path.relpath(OUT),
             os.path.getsize(OUT) / 1024))
    print("molecules cited: %d of %d in the library"
          % (len(cited), len(known)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
