#!/usr/bin/env python3
"""Build the PYTHIA glossary.

Checks that every cross-reference names a term that exists and that every
molecule cited is in the library. A dead cross-reference is worse than no
cross-reference: the reader assumes they missed something.

Also reports terms nothing links to, which usually means either the term
is not needed or an entry that should mention it does not.

Output: ../data/glossary.js
"""

import json
import os
import sys

from glossary import GLOSSARY, SOURCES as GLOSSARY_SOURCES
from library import LIBRARY
from sources import resolve

OUT = os.path.join(os.path.dirname(__file__), "..", "data", "glossary.js")


def main():
    known_molecules = set(entry.id for entry in LIBRARY)
    known_terms = set(t.term for t in GLOSSARY)
    problems = []
    linked_to = set()

    if len(known_terms) != len(GLOSSARY):
        problems.append("two entries share a term name")

    out = []
    for t in GLOSSARY:
        for ref in t.see:
            if ref not in known_terms:
                problems.append("'%s' points at '%s', which is not a term"
                                % (t.term, ref))
            else:
                linked_to.add(ref)
        for mol in t.molecules:
            if mol not in known_molecules:
                problems.append("'%s' cites unknown molecule '%s'"
                                % (t.term, mol))
        out.append({
            "term": t.term,
            "aka": t.aka,
            "definition": t.definition,
            "section": t.section,
            "see": list(t.see),
            "molecules": list(t.molecules),
        })

    if problems:
        print("FAILED:")
        for p in problems:
            print("  -", p)
        return 1

    out.sort(key=lambda e: e["term"].lower())
    payload = {"terms": out, "sources": resolve(GLOSSARY_SOURCES)}

    with open(OUT, "w", encoding="ascii") as fh:
        fh.write("/* PYTHIA glossary.\n"
                 "   Generated by tools/build_glossary.py -- "
                 "do not edit by hand.\n"
                 "   %d terms. */\n" % len(out))
        fh.write("window.PYTHIA_GLOSSARY = ")
        fh.write(json.dumps(payload, ensure_ascii=True,
                            separators=(",", ":")))
        fh.write(";\n")

    refs = sum(len(e["see"]) for e in out)
    orphans = sorted(known_terms - linked_to)
    print("built %d terms, %d cross-references -> %s (%.0f kB)"
          % (len(out), refs, os.path.relpath(OUT),
             os.path.getsize(OUT) / 1024))
    print("every cross-reference resolves")
    if orphans:
        print("%d term(s) nothing links to: %s"
              % (len(orphans), ", ".join(orphans)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
